[theme]
base = "dark"
primaryColor = "#21c647"
backgroundColor = "#1E1E1E"
secondaryBackgroundColor = "#2a2a2a"
dataframeHeaderBackgroundColor = "#343434"
textColor = "#FFFFFF"
borderColor = "#696969"
showWidgetBorder=true
font = "sans serif"
metricValueFontSize = "1.9rem"
codeFontSize = "0.875rem"
